version: '2.1'

volumes:
   geoserver-data:

services:
   db:
      image: kartoza/postgis:10.0-2.4
      volumes:
        - ./pg/postgres_data:/var/lib/postgresql
      ports:
        - "25433:5432"
      environment:
         - USERNAME=docker
         - PASS=docker
         - ALLOW_IP_RANGE=0.0.0.0/0
      restart: on-failure
      healthcheck:
        test: "exit 0"

   geoserver:
      image: kartoza/geoserver:2.13.0
      volumes:
        - ./geoserver_data:/opt/geoserver/data_dir
      ports:
        - "8600:8080"
      restart: on-failure
      env_file:
        - geoserver.env
      depends_on:
        db:
          condition: service_healthy
      healthcheck:
        test: curl --fail -s http://localhost:8080/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3

